[package]
name = "runner"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
tempfile = "3.10.1"
toml = "0.8.16"

[build-dependencies]
winres = "0.1.12"
